# Site settings
title: Neophiliac
description: Revolutionary by nature

# User settings
username: Neophiliac
user_description: No algorithms, no trackers, no adverts, no sponsors. Privacy policy: we don't collect or retain any data at all. Ever.</a>
user_title: Revolutionary by nature. 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
