# Site settings
title: Neophiliac
description: Revolutionary by nature

# User settings
username: Neophiliac
user_description: 
user_title: Revolutionary by nature. 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
