# Site settings
title: Neophiliac
description: Revolutionary by nature

# User settings
username: Neophiliac
user_description: We're serious about secure XMPP protocol messaging and presence information in the toughest network environments.</a>
user_title: Secure XMPP protocol messaging for low bandwidth, high latency and intermittent communication networks. 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
