# Site settings
title: XMPP Partners
description: Secure XMPP protocol messaging for low bandwidth, high latency and intermittent communication networks.

# User settings
username: XMPP Partners
user_description: We're serious about secure XMPP protocol messaging and presence information in the toughest network environments.</a>
user_title: Secure XMPP protocol messaging for low bandwidth, high latency and intermittent communication networks.
user_email: Instant message us at: dah@xmpp.partners

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
