# Site settings
title: Applied OpenBSD
description: The proactively secure Unix-like operating system.

# User settings
username: Applied OpenBSD
user_description: 
user_title: The proactively secure Unix-like operating system. 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
